#index:
#    path: /
#    controller: App\Controller\DefaultController::index

charlotte:
  path: /
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
  defaults:
    route: 'home'
    _locale: fr